export ZSH=/Users/calvm022/.oh-my-zsh

alias k='kubectl'
alias gj='get jobs'
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
unsetopt correct_all
plugins=(git urltools web-search wd bundle docker)

# User configuration

source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=$HOME/golang
export GOROOT=/usr/local/opt/go/libexec
export EDITOR='vim'
export JAVA_HOME="/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

#run rbenv on start
eval "$(rbenv init -)"

#alias'
alias vault='nocorrect vault'
alias gref='git show-ref $(current_branch)'
alias zshrc='vi ~/.zshrc'
alias G='grep'
alias GG='git grep'
alias docker_rm='docker rm $(docker ps -aq)'
alias docker_rmi='docker rmi $(docker images | grep "^<none>" | awk "{print $3}")'
alias a.='atom-beta .'
alias 'helm template'='nocorrect helm template'
alias 'rt'='TEST_MONGO_PORT=27019 bundle exec rake test'

alias bep='bundle exec pry -r ./config/environment'
alias rzr='ps aux | pgrep RzUpdater | xargs kill'
alias envsubst='/usr/local/Cellar/gettext/0.19.8.1/bin/envsubst'

export PATH="/usr/local/opt/curl/bin:$PATH"
