# This line changes for each machine
export ZSH=/Users/#{user}/.oh-my-zsh

# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
plugins=(git urltools web-search wd brew bundle docker)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/#{user}/Projects/Scripts"
source $ZSH/oh-my-zsh.sh
source "/usr/local/bin/virtualenvwrapper.sh"
export LANG=en_US.UTF-8
export SSH_KEY_PATH="~/.ssh/dsa_id"

#run rbenv on start
eval "$(rbenv init -)"

#init the docker gudz
. docker-machine-init

#alias'
alias gref='git show-ref $(current_branch)'
alias zshrc='vi ~/.zshrc'
alias G='grep'
alias GG='git grep'
alias gaeup='dev_appserver.py .'
alias pipit='pip freeze'
alias vactivate='. bin/activate'
